stages:
  - build
  - deploy

variables:
  SSH_PRIVATE_KEY: glpat-B6Q1antqDXskRxzmXSM_
  SSH_HOST: 159.89.172.93
  SSH_USER: root
  DEPLOY_PATH: /home/Kandradigital

before_script:
  - apt-get update -y
  - apt-get install -y openssh-client

build:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$SSH_HOST $SSH_PRIVATE_KEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh $SSH_USER@$SSH_HOST "mkdir -p $DEPLOY_PATH"
    - scp -r * $SSH_USER@$SSH_HOST:$DEPLOY_PATH

